apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"birthday","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"birthday"}},"template":{"metadata":{"labels":{"app":"birthday"}},"spec":{"containers":[{"image":"registry.digitalocean.com/birthday-registry/birthday-app:latest","name":"birthday-app","ports":[{"containerPort":5000}],"resources":{"limits":{"cpu":"500m","memory":"256Mi"},"requests":{"cpu":"100m","memory":"128Mi"}}}]}}}}
  creationTimestamp: "2025-06-29T22:58:54Z"
  generation: 10
  name: birthday
  namespace: default
  resourceVersion: "16599"
  uid: aa350676-3f98-40ef-bb46-e8c1727fd8c2
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: birthday
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-06-29T23:22:35Z"
      creationTimestamp: null
      labels:
        app: birthday
    spec:
      containers:
      - image: registry.digitalocean.com/birthday-registry/birthday-app:latest
        imagePullPolicy: Always
        name: birthday-app
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-06-29T22:58:54Z"
    lastUpdateTime: "2025-06-29T23:22:38Z"
    message: ReplicaSet "birthday-cb667888d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-06-29T23:30:34Z"
    lastUpdateTime: "2025-06-29T23:30:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 10
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
